# Generated by Django 4.2.10 on 2025-04-16 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the course')),
                ('duration', models.CharField(help_text="Duration of the course (e.g., '6 weeks')", max_length=50)),
                ('level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='BEG', help_text='Difficulty level of the course', max_length=3)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this course is featured on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the course was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the course was last updated')),
                ('instructor', models.ForeignKey(help_text='User who teaches this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When the user enrolled in the course')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('COM', 'Completed'), ('PAU', 'Paused'), ('DRO', 'Dropped')], default='ACT', help_text='Current status of the enrollment', max_length=3)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Percentage of course completion (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(help_text='Course that the user is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
                ('user', models.ForeignKey(help_text='User enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
