# Generated by Django 4.2.10 on 2025-04-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the module', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the module')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the module within the course')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the module was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the module was last updated')),
                ('course', models.ForeignKey(help_text='Course that this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
    ]
