# Generated by Django 4.2.10 on 2025-04-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the activity', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='lesson', help_text='Type of activity', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Content of the activity (e.g., lesson text, quiz questions)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the activity within the module')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the activity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the activity was last updated')),
                ('module', models.ForeignKey(help_text='Module that this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.module')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['module', 'order'],
            },
        ),
    ]
